#! /bin/sh

### DRACULA THEME
COLOR_BACKGROUND=#282a36
COLOR_CURRENT_LINE=#44475a
COLOR_FOREGROUND=#f8f8f2
COLOR_COMMENT=#6272a4
COLOR_CYAN=#8be9fd
COLOR_GREEN=#50fa7b
COLOR_ORANGE=#ffb86c
COLOR_PINK=#ff79c6
COLOR_PURPLE=#bd93f9
COLOR_RED=#ff5555
COLOR_YELLOW=#f1fa8c

### monitor
# to reconfigure monitors, run 'xrandr' to view available configurations
PRIMARY_MONITOR_NAME=DP-6
xrandr --output $PRIMARY_MONITOR_NAME --mode 3440x1440 --rate 144 --primary 
bspc monitor $PRIMARY_MONITOR_NAME -d I II III IV V 
#xrandr --output HDMI-A-0 --mode 1920x1080 --rate 60 --same-as DisplayPort-1 &
#xrandr --output HDMI-A-0 --mode 1920x1080 --rate 60 --left-of DisplayPort-1 
#bspc monitor HDMI-A-0 -d I II VI VII VIII IX X 


### power management
xset s off -dpms & ### disable Display Power Management Signaling. https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling

### theming
#nitrogen --set-centered $HOME/.config/assets/transparent.png --set-color=$COLOR_CURRENT_LINE
#nitrogen --restore & # nitrogen --save --set-centered /path/to/image.png

### keyboard
xset r rate 175 30 &

bspc config border_width           3
bspc config window_gap             4
bspc config top_padding            27
bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config normal_border_color    $COLOR_BACKGROUND
bspc config active_border_color    $COLOR_PURPLE
bspc config focused_border_color   $COLOR_PURPLE
bspc config presel_feedback_color  $COLOR_BACKGROUND
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a Firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
# bspc rule -a Code desktop='^2' 
# bspc config external_rules_command "$(which external_rules)"

### default programs to launch
/usr/bin/dunst &
firefox &
bspc rule -a --one-shot firefox desktop=2
firefox --private-window &
#code &


### status task bar
$HOME/.config/polybar/launch.sh &
# notify-send "Welcome" "Take a break and have a coffee while we initialize your system ..." --icon=  -h int:value:89
