#! /bin/sh

sxhkd &
picom & 

# monitor
xrandr --output DisplayPort-1 --mode 1920x1080 --rate 144 &
# disable Display Power Management Signaling. https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling
xset s off -dpms
# theming
nitrogen --restore & # nitrogen --save --set-centered /path/to/image.png
# keyboard
xset r rate 175 30 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4
bspc config top_padding          27

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

firefox &
code &
$HOME/.config/polybar/launch.sh
