



$dracula_theme_background = rgb(282a36)
$dracula_theme_currentline = rgb(44475a)
$dracula_theme_foreground = rgb(f8f8f2)
$dracula_theme_comment = rgb(6272a4)
$dracula_theme_cyan = rgb(8be9fd)
$dracula_theme_green = rgb(50fa7b)
$dracula_theme_orange = rgb(ffb86c)
$dracula_theme_pink = rgb(ff79c6)
$dracula_theme_purple = rgb(bd93f9)
$dracula_theme_red = rgb(ff5555)
$dracula_theme_yellow =rgb(f1fa8c)




background = $dracula_theme_orange
